#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_ADMIN_POINS_API.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DB_BELTPRO_SPUT_REPL")]
	public partial class BeltproDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertClientTran(ClientTran instance);
    partial void UpdateClientTran(ClientTran instance);
    partial void DeleteClientTran(ClientTran instance);
    #endregion
		
		public BeltproDataContext() :
                base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DB_BELTPRO_SPUT_REPLConnectionString"].ConnectionString, mappingSource)
        {
			OnCreated();
		}
		
		public BeltproDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BeltproDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BeltproDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ClientTran> ClientTrans
		{
			get
			{
				return this.GetTable<ClientTran>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ClientTrans")]
	public partial class ClientTran : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ClientTransId;
		
		private int _NodeId;
		
		private string _TransNo;
		
		private System.DateTime _StartDate;
		
		private string _NodeTrans;
		
		private System.Nullable<System.DateTime> _EndDate;
		
		private System.Nullable<double> _StartWeight;
		
		private System.Nullable<double> _EndWeight;
		
		private string _Kode;
		
		private System.Nullable<double> _Weight;
		
		private System.Nullable<double> _WeightPlan;
		
		private System.Nullable<double> _TPH;
		
		private System.Nullable<short> _Shift;
		
		private string _CompanyName;
		
		private string _BargeName;
		
		private string _BoatName;
		
		private string _Remarks;
		
		private string _WarningStatus;
		
		private string _Operator;
		
		private System.Nullable<bool> _flagSync;
		
		private System.Guid _rowguid;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnClientTransIdChanging(int value);
    partial void OnClientTransIdChanged();
    partial void OnNodeIdChanging(int value);
    partial void OnNodeIdChanged();
    partial void OnTransNoChanging(string value);
    partial void OnTransNoChanged();
    partial void OnStartDateChanging(System.DateTime value);
    partial void OnStartDateChanged();
    partial void OnNodeTransChanging(string value);
    partial void OnNodeTransChanged();
    partial void OnEndDateChanging(System.Nullable<System.DateTime> value);
    partial void OnEndDateChanged();
    partial void OnStartWeightChanging(System.Nullable<double> value);
    partial void OnStartWeightChanged();
    partial void OnEndWeightChanging(System.Nullable<double> value);
    partial void OnEndWeightChanged();
    partial void OnKodeChanging(string value);
    partial void OnKodeChanged();
    partial void OnWeightChanging(System.Nullable<double> value);
    partial void OnWeightChanged();
    partial void OnWeightPlanChanging(System.Nullable<double> value);
    partial void OnWeightPlanChanged();
    partial void OnTPHChanging(System.Nullable<double> value);
    partial void OnTPHChanged();
    partial void OnShiftChanging(System.Nullable<short> value);
    partial void OnShiftChanged();
    partial void OnCompanyNameChanging(string value);
    partial void OnCompanyNameChanged();
    partial void OnBargeNameChanging(string value);
    partial void OnBargeNameChanged();
    partial void OnBoatNameChanging(string value);
    partial void OnBoatNameChanged();
    partial void OnRemarksChanging(string value);
    partial void OnRemarksChanged();
    partial void OnWarningStatusChanging(string value);
    partial void OnWarningStatusChanged();
    partial void OnOperatorChanging(string value);
    partial void OnOperatorChanged();
    partial void OnflagSyncChanging(System.Nullable<bool> value);
    partial void OnflagSyncChanged();
    partial void OnrowguidChanging(System.Guid value);
    partial void OnrowguidChanged();
    #endregion
		
		public ClientTran()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClientTransId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ClientTransId
		{
			get
			{
				return this._ClientTransId;
			}
			set
			{
				if ((this._ClientTransId != value))
				{
					this.OnClientTransIdChanging(value);
					this.SendPropertyChanging();
					this._ClientTransId = value;
					this.SendPropertyChanged("ClientTransId");
					this.OnClientTransIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NodeId", DbType="Int NOT NULL")]
		public int NodeId
		{
			get
			{
				return this._NodeId;
			}
			set
			{
				if ((this._NodeId != value))
				{
					this.OnNodeIdChanging(value);
					this.SendPropertyChanging();
					this._NodeId = value;
					this.SendPropertyChanged("NodeId");
					this.OnNodeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransNo", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string TransNo
		{
			get
			{
				return this._TransNo;
			}
			set
			{
				if ((this._TransNo != value))
				{
					this.OnTransNoChanging(value);
					this.SendPropertyChanging();
					this._TransNo = value;
					this.SendPropertyChanged("TransNo");
					this.OnTransNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartDate", DbType="DateTime NOT NULL")]
		public System.DateTime StartDate
		{
			get
			{
				return this._StartDate;
			}
			set
			{
				if ((this._StartDate != value))
				{
					this.OnStartDateChanging(value);
					this.SendPropertyChanging();
					this._StartDate = value;
					this.SendPropertyChanged("StartDate");
					this.OnStartDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NodeTrans", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string NodeTrans
		{
			get
			{
				return this._NodeTrans;
			}
			set
			{
				if ((this._NodeTrans != value))
				{
					this.OnNodeTransChanging(value);
					this.SendPropertyChanging();
					this._NodeTrans = value;
					this.SendPropertyChanged("NodeTrans");
					this.OnNodeTransChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> EndDate
		{
			get
			{
				return this._EndDate;
			}
			set
			{
				if ((this._EndDate != value))
				{
					this.OnEndDateChanging(value);
					this.SendPropertyChanging();
					this._EndDate = value;
					this.SendPropertyChanged("EndDate");
					this.OnEndDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartWeight", DbType="Float")]
		public System.Nullable<double> StartWeight
		{
			get
			{
				return this._StartWeight;
			}
			set
			{
				if ((this._StartWeight != value))
				{
					this.OnStartWeightChanging(value);
					this.SendPropertyChanging();
					this._StartWeight = value;
					this.SendPropertyChanged("StartWeight");
					this.OnStartWeightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndWeight", DbType="Float")]
		public System.Nullable<double> EndWeight
		{
			get
			{
				return this._EndWeight;
			}
			set
			{
				if ((this._EndWeight != value))
				{
					this.OnEndWeightChanging(value);
					this.SendPropertyChanging();
					this._EndWeight = value;
					this.SendPropertyChanged("EndWeight");
					this.OnEndWeightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kode", DbType="VarChar(10)")]
		public string Kode
		{
			get
			{
				return this._Kode;
			}
			set
			{
				if ((this._Kode != value))
				{
					this.OnKodeChanging(value);
					this.SendPropertyChanging();
					this._Kode = value;
					this.SendPropertyChanged("Kode");
					this.OnKodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weight", DbType="Float")]
		public System.Nullable<double> Weight
		{
			get
			{
				return this._Weight;
			}
			set
			{
				if ((this._Weight != value))
				{
					this.OnWeightChanging(value);
					this.SendPropertyChanging();
					this._Weight = value;
					this.SendPropertyChanged("Weight");
					this.OnWeightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WeightPlan", DbType="Float")]
		public System.Nullable<double> WeightPlan
		{
			get
			{
				return this._WeightPlan;
			}
			set
			{
				if ((this._WeightPlan != value))
				{
					this.OnWeightPlanChanging(value);
					this.SendPropertyChanging();
					this._WeightPlan = value;
					this.SendPropertyChanged("WeightPlan");
					this.OnWeightPlanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TPH", DbType="Float")]
		public System.Nullable<double> TPH
		{
			get
			{
				return this._TPH;
			}
			set
			{
				if ((this._TPH != value))
				{
					this.OnTPHChanging(value);
					this.SendPropertyChanging();
					this._TPH = value;
					this.SendPropertyChanged("TPH");
					this.OnTPHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Shift", DbType="SmallInt")]
		public System.Nullable<short> Shift
		{
			get
			{
				return this._Shift;
			}
			set
			{
				if ((this._Shift != value))
				{
					this.OnShiftChanging(value);
					this.SendPropertyChanging();
					this._Shift = value;
					this.SendPropertyChanged("Shift");
					this.OnShiftChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyName", DbType="VarChar(50)")]
		public string CompanyName
		{
			get
			{
				return this._CompanyName;
			}
			set
			{
				if ((this._CompanyName != value))
				{
					this.OnCompanyNameChanging(value);
					this.SendPropertyChanging();
					this._CompanyName = value;
					this.SendPropertyChanged("CompanyName");
					this.OnCompanyNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BargeName", DbType="VarChar(50)")]
		public string BargeName
		{
			get
			{
				return this._BargeName;
			}
			set
			{
				if ((this._BargeName != value))
				{
					this.OnBargeNameChanging(value);
					this.SendPropertyChanging();
					this._BargeName = value;
					this.SendPropertyChanged("BargeName");
					this.OnBargeNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BoatName", DbType="VarChar(50)")]
		public string BoatName
		{
			get
			{
				return this._BoatName;
			}
			set
			{
				if ((this._BoatName != value))
				{
					this.OnBoatNameChanging(value);
					this.SendPropertyChanging();
					this._BoatName = value;
					this.SendPropertyChanged("BoatName");
					this.OnBoatNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remarks", DbType="VarChar(30)")]
		public string Remarks
		{
			get
			{
				return this._Remarks;
			}
			set
			{
				if ((this._Remarks != value))
				{
					this.OnRemarksChanging(value);
					this.SendPropertyChanging();
					this._Remarks = value;
					this.SendPropertyChanged("Remarks");
					this.OnRemarksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WarningStatus", DbType="VarChar(20)")]
		public string WarningStatus
		{
			get
			{
				return this._WarningStatus;
			}
			set
			{
				if ((this._WarningStatus != value))
				{
					this.OnWarningStatusChanging(value);
					this.SendPropertyChanging();
					this._WarningStatus = value;
					this.SendPropertyChanged("WarningStatus");
					this.OnWarningStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Operator", DbType="VarChar(20)")]
		public string Operator
		{
			get
			{
				return this._Operator;
			}
			set
			{
				if ((this._Operator != value))
				{
					this.OnOperatorChanging(value);
					this.SendPropertyChanging();
					this._Operator = value;
					this.SendPropertyChanged("Operator");
					this.OnOperatorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_flagSync", DbType="Bit")]
		public System.Nullable<bool> flagSync
		{
			get
			{
				return this._flagSync;
			}
			set
			{
				if ((this._flagSync != value))
				{
					this.OnflagSyncChanging(value);
					this.SendPropertyChanging();
					this._flagSync = value;
					this.SendPropertyChanged("flagSync");
					this.OnflagSyncChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rowguid", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid rowguid
		{
			get
			{
				return this._rowguid;
			}
			set
			{
				if ((this._rowguid != value))
				{
					this.OnrowguidChanging(value);
					this.SendPropertyChanging();
					this._rowguid = value;
					this.SendPropertyChanged("rowguid");
					this.OnrowguidChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
